#ifndef __CAPS_PHYSICS_DEFINE__
#define __CAPS_PHYSICS_DEFINE__
#ifndef BT_COLLISION_OBJECT_H

#define BT_ACTIVE_TAG 1
#define BT_ISLAND_SLEEPING 2
#define BT_WANTS_DEACTIVATION 3
#define BT_DISABLE_DEACTIVATION 4
#define BT_DISABLE_SIMULATION 5

#endif
#endif //!__CAPS_PHYSICS_DEFINE__
